### ISSUE TITLE
react-native-youtube requires Play services

### ISSUE THREAD

**Issue by singuliere** [PierreBresson/Cause-Commune#2]
This dependency [blocks the inclusion in f-droid](https://gitlab.com/fdroid/rfp/issues/981#note_216490763). Would it be possible to remove / replace it ?

Thanks a lot for your work :-)

**Comment by PierreBresson** [comment]
Thanks for your help! Can't wait to see the app in f-droid store 👌 
Youtube is now removed from the app : https://github.com/PierreBresson/Cause-Commune/commit/97dad1c8d9a6e77ed4bc3a958d63ba6e148ca4d1

**Comment by PierreBresson** [comment]
@singuliere What if I want to push an update to f-droid store?

**Comment by licaon-kter** [comment]
@PierreBresson Start tagging reliably ;)

> Youtube is now removed from the app : 97dad1c

Nice, but... a new release would be nicer, eg `v1.0.2` without this dependency

> What if I want to push an update to f-droid store?

If you tag reliably, eg. code more, update [versionCode](https://github.com/PierreBresson/Cause-Commune/blob/master/android/app/build.gradle#L110) and versionNamw to `1.0.3`, then release/tag `v1.0.3`  etc, we can enable autoupdate and the fdroidbot can pickup new versions by itself

**Comment by PierreBresson** [comment]
@licaon-kter Alright, I see. I've updated both the [versionCode](https://github.com/PierreBresson/Cause-Commune/blob/318d51f9693ad3e4a0600e739f1e0f9498f3d371/android/app/build.gradle#L110) and the [tagging](https://github.com/PierreBresson/Cause-Commune/releases/tag/v1.0.2). Hope it's fine now.
